<?php

namespace MobileFrontend\Transforms;

use Wikimedia\Parsoid\Core\DOMCompat;
use Wikimedia\Parsoid\DOM\Document;
use Wikimedia\Parsoid\DOM\Element;

/**
 * Collapse the lead infoboxes into a "Quick facts" section.
 *
 * Detaches every infobox from the lead of an article and re-presents them
 * under a shared "Quick facts" heading, immediately after the lead text and
 * before the first real section, at all screen widths. Infoboxes outside the
 * lead are left untouched. Because this happens server-side, the section is
 * in the initial HTML and never reflows (no layout shift), and it reuses the
 * existing mobile section-collapsing logic so it collapses/expands like any
 * other section.
 *
 * The transform runs from ExtMobileFrontend::domParseMobile(), after the page
 * has been split into sections. It builds the new section in whichever of two
 * shapes matches how the page was sectioned (Parsoid or legacy).
 *
 * Parsoid output is already split into `<section data-mw-section-id="…">`, and
 * `sectionCollapsing.js` looks for elements matching
 * `.mw-parser-output > section > .mw-heading`, so the heading goes inside the
 * section:
 *
 *       <section class="mf-quick-facts">
 *         <div class="mw-heading mw-heading2"><h2 id="…">Quick facts</h2></div>
 *         <div class="mf-quick-facts__content"><!-- infoboxes --></div>
 *       </section>
 *
 * Legacy parser output is split by MakeSectionsTransform, which runs earlier
 * and leaves headings as siblings of the section they open. `Toggler.js` pairs
 * a `.section-heading` with its next sibling `<section>`, so the heading
 * precedes the section. `collapsible-block` keeps the section closed until
 * Toggler.js takes over:
 *
 *       <div class="mw-heading mw-heading2 section-heading">
 *         <span class="indicator …"></span><h2 id="…">Quick facts</h2>
 *       </div>
 *       <section class="mf-quick-facts collapsible-block">
 *         <div class="mf-quick-facts__content"><!-- infoboxes --></div>
 *       </section>
 *
 * The legacy section deliberately carries no `mf-section-N` class or id.
 * MakeSectionsTransform assigns section numbers sequentially as it counts the
 * headings, and claiming one here would renumber every section after it, which
 * would shift the section numbers that edit links point at. Toggler.js pairs a
 * heading with whatever <section> follows it, so it doesn't need the class to
 * work. Tradeoff: We lose the interim pre-JS onclick handler (mfTempOpenSection)
 * that lets a tap open a section before the JS loads. The interim handler looks
 * the section up by its `mf-section-N` id so with none to find, the heading
 * doesn't get it.
 *
 * When there are no infoboxes in the lead, or the page was never split into
 * sections, the transform is a no-op.
 *
 * @see IMobileTransform
 */
class QuickFactsTransform implements IMobileTransform {

	/**
	 * ID given to the generated heading, in both parser shapes. Under Parsoid,
	 * sectionCollapsing.js also builds the content element's id from it
	 * (`<id>-collapsible-content`). Under legacy, Toggler.js ignores this id
	 * and numbers the content element itself instead.
	 */
	private const HEADING_ID = 'mf-quick-facts';

	/** Parsoid's lead section. */
	private const PARSOID_LEAD_SELECTOR = 'section[data-mw-section-id="0"]';

	/** MakeSectionsTransform's lead section, for legacy parser output. */
	private const LEGACY_LEAD_SELECTOR = 'section#mf-section-0';

	/**
	 * @param string $headingText Localized label for the section heading.
	 * @param bool $isParsoidOutput Whether the content was generated by Parsoid.
	 */
	public function __construct(
		private readonly string $headingText,
		private readonly bool $isParsoidOutput,
	) {
	}

	/**
	 * @inheritDoc
	 */
	public function apply( Element $node ): void {
		$leadSection = DOMCompat::querySelector( $node, $this->isParsoidOutput ?
			self::PARSOID_LEAD_SELECTOR : self::LEGACY_LEAD_SELECTOR );
		if ( !$leadSection instanceof Element ) {
			return;
		}

		$infoboxes = $this->identifyInfoboxes( $leadSection );
		if ( !$infoboxes ) {
			return;
		}

		$parent = $leadSection->parentNode;
		$doc = $node->ownerDocument;
		if ( $parent === null || $doc === null ) {
			return;
		}

		// Insert immediately after the lead section, before the first real section.
		$nextSibling = $leadSection->nextSibling;
		foreach ( $this->buildSection( $doc, $infoboxes ) as $element ) {
			$parent->insertBefore( $element, $nextSibling );
		}
	}

	/**
	 * Build the Quick facts heading and section in the shape this page's parser
	 * expects. See the class comment for the two shapes.
	 *
	 * @param Document $doc
	 * @param Element[] $infoboxes
	 * @return Element[] Elements to insert after the lead section, in order.
	 */
	private function buildSection( Document $doc, array $infoboxes ): array {
		$section = $doc->createElement( 'section' );

		if ( $this->isParsoidOutput ) {
			$section->setAttribute( 'class', 'mf-quick-facts' );
			$section->appendChild( $this->buildHeading( $doc ) );
			$section->appendChild( $this->buildContent( $doc, $infoboxes ) );

			return [ $section ];
		}

		// `collapsible-block` is what keeps a legacy section closed until Toggler.js
		// takes over, so Quick facts starts closed like every other section instead
		// of showing open and then snapping shut once JavaScript runs.
		$section->setAttribute(
			'class',
			'mf-quick-facts ' . MakeSectionsTransform::STYLE_COLLAPSIBLE_SECTION_CLASS
		);
		$section->appendChild( $this->buildContent( $doc, $infoboxes ) );

		return [ $this->buildHeading( $doc ), $section ];
	}

	/**
	 * Find every infobox to move, walking each up to the highest ancestor that
	 * is still a direct child of the lead section so any wrapping element
	 * moves with it. Infoboxes sharing the same wrapper are only returned once.
	 *
	 * @param Element $leadSection
	 * @return Element[]
	 */
	private function identifyInfoboxes( Element $leadSection ): array {
		$wrappers = [];
		foreach ( DOMCompat::querySelectorAll( $leadSection, '.infobox' ) as $infobox ) {
			// Walk up to the direct child of the lead section that contains the
			// infobox, so infoboxes wrapped in another element like .mw-stack or
			// .collapsible move cleanly.
			$node = $infobox;
			while (
				$node->parentNode instanceof Element &&
				!$node->parentNode->isSameNode( $leadSection )
			) {
				$node = $node->parentNode;
			}

			$alreadyFound = false;
			foreach ( $wrappers as $wrapper ) {
				if ( $wrapper->isSameNode( $node ) ) {
					$alreadyFound = true;
					break;
				}
			}
			if ( !$alreadyFound ) {
				$wrappers[] = $node;
			}
		}

		return $wrappers;
	}

	/**
	 * Build the heading for the Quick facts section.
	 *
	 * Both parsers wrap headings in `<div class="mw-heading mw-heading2">`. For
	 * legacy output the wrapper also gets the `section-heading` class and the
	 * arrow placeholder that MakeSectionsTransform::prepareHeading() adds to a
	 * real section heading, minus the `onclick` (see the class comment).
	 * Toggler.js looks for the wrapper, so it has to match.
	 *
	 * @param Document $doc
	 * @return Element
	 */
	private function buildHeading( Document $doc ): Element {
		$heading = $doc->createElement( 'h2' );
		$heading->setAttribute( 'id', self::HEADING_ID );
		$heading->textContent = $this->headingText;

		$wrapper = $doc->createElement( 'div' );
		$wrapper->setAttribute( 'class', 'mw-heading mw-heading2' );
		$wrapper->appendChild( $heading );

		if ( $this->isParsoidOutput ) {
			return $wrapper;
		}

		// This class is what makes Toggler.js collapse the section. Toggler.js
		// also counts every `.section-heading` it finds, to pair each heading
		// with its content div (aria-controls ids). That count is separate
		// from the mf-section-N numbering MakeSectionsTransform hands out
		// server-side. Quick facts gets counted here too, shifting the
		// pairing numbers for headings after it, but that is harmless since
		// nothing outside Toggler.js reads them.
		$wrapper->setAttribute( 'class', 'mw-heading mw-heading2 section-heading' );

		// Placeholder for the collapse/expand arrow that Toggler.js swaps in, so
		// the heading does not shift when the real icon arrives.
		$indicator = $doc->createElement( 'span' );
		$indicator->setAttribute( 'class', 'indicator mf-icon mf-icon-expand mf-icon--small' );
		$wrapper->insertBefore( $indicator, $wrapper->firstChild );

		return $wrapper;
	}

	/**
	 * Wrap the infoboxes in the collapsible content element.
	 *
	 * @param Document $doc
	 * @param Element[] $infoboxes
	 * @return Element
	 */
	private function buildContent( Document $doc, array $infoboxes ): Element {
		// The heading's next sibling becomes the collapsible content, so the
		// infoboxes must be wrapped in a `<div>`.
		$content = $doc->createElement( 'div' );
		$content->setAttribute( 'class', 'mf-quick-facts__content' );
		foreach ( $infoboxes as $infobox ) {
			$content->appendChild( $infobox );
		}

		return $content;
	}
}
