#!/usr/bin/python
import sys
import urllib2
import subprocess
import json

def get_project():
    command = "git remote -v | head -n1 | awk '{print $2}' | sed -e 's,.*:\(.*/\)\?,,' -e 's/\.git$//'"
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

    #Launch the shell command:
    output, error = process.communicate()
    return "/".join( output.split('/')[-3:] ).replace( '\n', '' )

def query_gerrit(project):
    url = "https://gerrit.wikimedia.org/r/changes/?q=status:open+project:" \
        + project + "&n=25&O=1"
    req = urllib2.Request(url)
    req.add_header('Accept',
                   'application/json,application/json,application/jsonrequest')
    req.add_header('Content-Type', "application/json; charset=UTF-8")
    resp, data = urllib2.urlopen(req)
    data = json.loads(data)
    return data

changes = query_gerrit(get_project())
open_patches = 0
for change in changes:
    reviews = change["labels"]["Code-Review"]
    if 'disliked' not in reviews and 'rejected' not in reviews and 'approved' not in reviews:
        open_patches += 1

if open_patches > 5:
    print 'Do some code review first! There are %s open unreviewed patches!' % open_patches
    print 'You can still send this review but note this will generate bad karma by running `git review master --no-custom-script`.'
    sys.exit(1)
