#!/bin/sh
# First you will need to install jshint
# Enable this pre-commit hook by executing the following from the project root directory
# $ ln -s $PWD/scripts/pre-commit .git/hooks/pre-commit
if git diff --name-only --cached | grep -P '\.less$' ; then
	make less
fi
make jshint
if git diff --name-only --cached | grep -P '\.js$' ; then
	make qunit
fi
if git diff --name-only --cached | grep -P 'includes/skins/.*php$' ; then
	make validatehtml
fi
for file in `git diff --cached --name-only | grep ".png\$"`
do
	[ -f $file ] && echo "Compressing $file" &&  \
		optipng -q -o7 "$file" && advpng -z -4 "$file" && advdef -z -4 "$file" | grep "Output" || echo 'png was removed'
done
